name: Deploy Flask Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted # Ensure this matches your self-hosted runner's label
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Update 
        run: |
          apt update -y
          apt install docker.io -y
          
      - name: Build Docker image
        run: docker build . -t my-flask-app

      - name: Run Docker container
        run: |
          docker run -d --name flask-app -p 5000:5000 \
          -e AWS_ACCESS_KEY="${{ secrets.AWS_ACCESS_KEY }}" \
          -e AWS_SECRET_KEY="${{ secrets.AWS_SECRET_KEY }}" \
          -e S3_BUCKET="${{ secrets.S3_BUCKET }}" \
          my-flask-app
