name: Deploy Flask Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted # Ensure this matches your self-hosted runner's label
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Update 
        run: |
          ls
          sudo apt update -y && sudo apt install docker.io -y
          sudo docker kill flaskapp || true
          sudo docker rm -f flask-app || true
          
          
      - name: Build Docker image
        run: sudo docker build -f ChatBot/Dockerfile -t my-flask-app ChatBot

      - name: Run Docker container
        run: |
          
          sudo docker run -d --name flask-app -p 5000:5000 \
          -e AWS_ACCESS_KEY="${{ secrets.AWS_ACCESS_KEY }}" \
          -e AWS_SECRET_KEY="${{ secrets.AWS_SECRET_KEY }}" \
          -e S3_BUCKET="${{ secrets.S3_BUCKET }}" \
          my-flask-app
